version: '3.3'

services:
    bot:
        image: "${BOT_NAME:-tg_bot-image}"
        container_name: "${BOT_NAME:-tg_bot-container}"
        stop_signal: SIGINT
        build:
            context: .
        volumes:
            - .:/"${BOT_NAME}"
        command: python3 app.py

        restart: always
        networks:
            - tg_bot

        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - database:/data/db
        ports:
            - 27017:27018


    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27018/



networks:
    tg_bot:
        driver: bridge

